import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { FaArrowLeft, FaArrowRight, FaCalendarDays, FaCheck, FaLocationDot } from 'react-icons/fa6'
import { api, authApi } from '../lib/api.js'
import './PortalPages.css'

export default function TicketingPage(){
  const [events,setEvents]=useState([]),[selected,setSelected]=useState(null),[ticket,setTicket]=useState(null),[notice,setNotice]=useState('')
  const [user,setUser]=useState(undefined),[organizer,setOrganizer]=useState(null),[myEvents,setMyEvents]=useState([])
  const loadPublic=()=>api('/ticketing/events').then(data=>setEvents(data.events)).catch(error=>setNotice(error.message))
  useEffect(()=>{loadPublic();authApi.session().then(({user:current})=>{setUser(current);if(current)api('/ticketing/organizer').then(data=>setOrganizer(data.organizer))}).catch(()=>setUser(null))},[])
  useEffect(()=>{if(organizer?.status==='approved')api('/ticketing/organizer/events').then(data=>setMyEvents(data.events)).catch(error=>setNotice(error.message))},[organizer])
  return <div className="portal-page ticketing-page"><header className="portal-header"><Link to="/" className="portal-brand"><img src="/brand/lions-ent-white.png" alt="Lions Entertainment"/></Link><nav><a href="#events">Events</a><a href="#organizer">Organizer portal</a><Link className="portal-login" to="/login">Login</Link></nav></header>
    {notice&&<div className="booking-toast error"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
    <main><section className="ticketing-hero portal-shell"><p className="portal-eyebrow">Lions Entertainment Ticketing</p><h1>Register. Arrive.<br/><span>Enter smoothly.</span></h1><p>Discover events, reserve your place and receive a secure QR ticket for entrance.</p><a className="portal-button primary" href="#events">Explore events <FaArrowRight/></a></section>
      <section className="portal-section portal-shell" id="events"><div className="portal-heading"><p className="portal-eyebrow">Upcoming events</p><h2>Choose your event</h2></div><div className="ticket-event-grid">{events.length?events.map(event=><article key={event.id}><div className="ticket-event-date"><FaCalendarDays/><span>{new Date(event.starts_at).toLocaleDateString()}</span></div><h3>{event.title}</h3><p><FaLocationDot/> {event.venue}</p><small>Hosted by {event.organization_name}</small><div className="capacity"><span>{event.registered} registered</span><strong>{Math.max(0,event.capacity-event.registered)} places left</strong></div><button className="portal-button primary" disabled={event.registered>=event.capacity} onClick={()=>setSelected(event)}>{event.registered>=event.capacity?'Event full':'Register'} <FaArrowRight/></button></article>):<p className="ticket-empty">No public events are available yet.</p>}</div></section>
      <section className="portal-section process-section" id="organizer"><div className="portal-shell booking-section-content"><div className="portal-heading"><p className="portal-eyebrow">Organizer portal</p><h2>Manage registrations and entrance</h2></div>{user===undefined?<p>Checking your account…</p>:!user?<p>Sign in with an account created by Lions Entertainment to request organizer access. <Link to="/login">Log in</Link></p>:!organizer?<OrganizerApplication onDone={()=>api('/ticketing/organizer').then(data=>setOrganizer(data.organizer))} setNotice={setNotice}/>:organizer.status!=='approved'?<div className="organizer-status"><strong>Application {organizer.status}</strong><p>An administrator must approve your organizer account before you can create events.</p></div>:<OrganizerWorkspace events={myEvents} reload={()=>api('/ticketing/organizer/events').then(data=>setMyEvents(data.events))} setNotice={setNotice}/>}</div></section>
    </main><footer className="portal-footer portal-shell"><span>© 2026 Lions Entertainment</span><Link to="/"><FaArrowLeft/> Main website</Link></footer>
    {selected&&<RegistrationModal event={selected} close={()=>setSelected(null)} success={value=>{setTicket(value);setSelected(null);loadPublic()}} setNotice={setNotice}/>} {ticket&&<TicketModal ticket={ticket} close={()=>setTicket(null)}/>}</div>
}

function OrganizerApplication({onDone,setNotice}){const[form,setForm]=useState({organizationName:'',phone:'',reason:''});async function submit(e){e.preventDefault();try{await api('/ticketing/organizer/apply',{method:'POST',body:JSON.stringify(form)});setNotice('Organizer application submitted for approval.');onDone()}catch(error){setNotice(error.message)}}return <form className="ticket-form light" onSubmit={submit}><label>Organization or client name<input required value={form.organizationName} onChange={e=>setForm({...form,organizationName:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Why do you need Ticketing?<textarea rows="4" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className="portal-button primary">Request organizer access</button></form>}

function OrganizerWorkspace({events,reload,setNotice}){const[form,setForm]=useState({title:'',description:'',venue:'',startsAt:'',endsAt:'',capacity:'',registrationDeadline:'',publish:true}),[manage,setManage]=useState(null);async function create(e){e.preventDefault();try{await api('/ticketing/organizer/events',{method:'POST',body:JSON.stringify(form)});setNotice('Event created.');setForm({title:'',description:'',venue:'',startsAt:'',endsAt:'',capacity:'',registrationDeadline:'',publish:true});reload()}catch(error){setNotice(error.message)}}return <div className="organizer-workspace"><form className="ticket-form light" onSubmit={create}><h3>Create an event</h3><label>Event title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Venue<input required value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label><div className="form-grid"><label>Starts<input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div><label>Venue capacity<input required min="1" type="number" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label><label>Registration deadline<input type="datetime-local" value={form.registrationDeadline} onChange={e=>setForm({...form,registrationDeadline:e.target.value})}/></label><label>Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="ticket-check"><input type="checkbox" checked={form.publish} onChange={e=>setForm({...form,publish:e.target.checked})}/> Publish immediately</label><button className="portal-button primary">Create event</button></form><div className="organizer-events"><h3>My events</h3>{events.map(event=><button key={event.id} onClick={()=>setManage(event)}><strong>{event.title}</strong><span>{event.registered}/{event.capacity} registered · {event.status}</span></button>)}</div>{manage&&<GuestManager event={manage} close={()=>setManage(null)} setNotice={setNotice}/>}</div>}

function RegistrationModal({event,close,success,setNotice}){const[form,setForm]=useState({fullName:'',email:'',phone:''});async function submit(e){e.preventDefault();try{const data=await api(`/ticketing/events/${event.id}/register`,{method:'POST',body:JSON.stringify(form)});success(data.ticket)}catch(error){setNotice(error.message)}}return <div className="ticket-modal"><form className="ticket-form" onSubmit={submit}><button type="button" className="ticket-close" onClick={close}>×</button><p className="portal-eyebrow">Event registration</p><h2>{event.title}</h2><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><button className="portal-button primary">Confirm registration</button></form></div>}

function TicketModal({ticket,close}){const value=`LIONS:${ticket.qrToken}`;return <div className="ticket-modal"><div className="issued-ticket"><button className="ticket-close" onClick={close}>×</button><FaCheck className="ticket-success"/><p className="portal-eyebrow">Registration confirmed</p><h2>{ticket.eventTitle}</h2><QRCodeSVG value={value} size={190} level="H"/><strong>{ticket.fullName}</strong><span>{ticket.ticketCode}</span><p>Present this QR code or your name at the entrance.</p></div></div>}

function GuestManager({event,close,setNotice}){const[attendees,setAttendees]=useState([]),[search,setSearch]=useState('');const load=()=>api(`/ticketing/organizer/events/${event.id}/attendees`).then(data=>setAttendees(data.attendees)).catch(error=>setNotice(error.message));useEffect(()=>{let active=true;api(`/ticketing/organizer/events/${event.id}/attendees`).then(data=>{if(active)setAttendees(data.attendees)}).catch(error=>setNotice(error.message));return()=>{active=false}},[event.id,setNotice]);async function checkIn(e){e.preventDefault();const query=search.startsWith('LIONS:')?search.slice(6):search;try{const data=await api(`/ticketing/organizer/events/${event.id}/check-in`,{method:'POST',body:JSON.stringify({query})});setNotice(`${data.guest.full_name} checked in successfully.`);setSearch('');load()}catch(error){setNotice(error.message)}}return <div className="ticket-modal"><div className="guest-manager"><button className="ticket-close" onClick={close}>×</button><h2>{event.title}</h2><form onSubmit={checkIn}><input required placeholder="Guest name, ticket code or QR value" value={search} onChange={e=>setSearch(e.target.value)}/><button className="portal-button primary">Check in</button></form><p>{attendees.filter(a=>a.status==='checked_in').length} entered · {attendees.length} registered</p><div className="guest-list">{attendees.map(a=><div key={a.id}><strong>{a.full_name}</strong><span>{a.ticket_code}</span><small>{a.status.replace('_',' ')}</small></div>)}</div></div></div>}
