import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { FaCalendarDays, FaCheck, FaClock, FaLocationDot, FaTicket, FaXmark } from 'react-icons/fa6'
import { api, authApi } from '../lib/api.js'
import './PortalPages.css'

export default function TicketPage(){
  const {token}=useParams(),[ticket,setTicket]=useState(null),[error,setError]=useState(''),[canManage,setCanManage]=useState(false),[checkingIn,setCheckingIn]=useState(false),[notice,setNotice]=useState('')
  const loadTicket=()=>api(`/ticketing/tickets/${token}`).then(data=>setTicket(data.ticket))
  useEffect(()=>{let active=true;api(`/ticketing/tickets/${token}`).then(data=>{if(active)setTicket(data.ticket)}).catch(reason=>{if(active)setError(reason.message)});authApi.session().then(()=>api(`/ticketing/tickets/${token}/access`)).then(data=>{if(active)setCanManage(data.canManage)}).catch(()=>{});return()=>{active=false}},[token])
  async function markUsed(){setCheckingIn(true);setNotice('');try{await api(`/ticketing/tickets/${token}/check-in`,{method:'POST'});await loadTicket();setNotice('Ticket marked as used. The guest may enter.')}catch(reason){setNotice(reason.message)}finally{setCheckingIn(false)}}
  return <main className="portal-page ticket-verify-page"><Link className="ticket-verify-brand" to="/"><img src="/brand/lions-plus-white.png" alt="Lions Plus"/></Link>{error?<section className="ticket-verify-card invalid"><FaXmark/><p className="portal-eyebrow">Ticket verification</p><h1>Ticket not found</h1><p>{error}</p><Link className="portal-button primary" to="/ticketing">View events</Link></section>:!ticket?<p>Verifying ticket…</p>:<section className="ticket-verify-card"><div className={`ticket-validity ${ticket.status}`}>{ticket.status==='cancelled'?<FaXmark/>:<FaCheck/>}<span>{ticket.status==='registered'?'Valid ticket':ticket.status==='checked_in'?'Already checked in':'Ticket cancelled'}</span></div><p className="portal-eyebrow">Verified digital ticket</p><h1>{ticket.title}</h1><div className="ticket-holder"><span>Guest</span><strong>{ticket.full_name}</strong><small><FaTicket/> {ticket.ticket_code}</small></div><dl><div><dt><FaCalendarDays/> Date</dt><dd>{new Date(ticket.starts_at).toLocaleDateString()}</dd></div><div><dt><FaClock/> Time</dt><dd>{new Date(ticket.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt><FaLocationDot/> Venue</dt><dd>{ticket.venue}</dd></div><div><dt>Organizer</dt><dd>{ticket.organization_name}</dd></div></dl>{ticket.checked_in_at&&<p className="ticket-entry-time">Entered {new Date(ticket.checked_in_at).toLocaleString()}</p>}{canManage&&ticket.status==='registered'&&<div className="ticket-gate-action"><p>Organizer entrance control</p><button className="portal-button primary" disabled={checkingIn} onClick={markUsed}>{checkingIn?'Marking…':'Mark ticket used'}</button></div>}{canManage&&notice&&<p className="ticket-gate-notice">{notice}</p>}<p className="ticket-verify-note">Entrance staff should confirm the guest’s identity before admission.</p></section>}</main>
}
